# Generated by Django 3.0.4 on 2020-03-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=255, verbose_name='사이트 내 식별자')),
                ('url', models.CharField(max_length=1023, verbose_name='게시글 주소')),
                ('site_url', models.CharField(max_length=1023, verbose_name='사이트 주소')),
                ('site_name', models.CharField(max_length=255, verbose_name='사이트 이름')),
                ('content', models.CharField(max_length=1023, verbose_name='내용')),
                ('post_created_at', models.DateTimeField(blank=True, verbose_name='게시글 생성일자')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일자')),
                ('edited_at', models.DateTimeField(auto_now=True, verbose_name='수정일자')),
            ],
            options={
                'verbose_name': '크롤링한 정보',
                'verbose_name_plural': '크롤링한 정보들',
            },
        ),
    ]
